Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--audio", "none"]
  end

  (1..2).each do |n|
    config.vm.define "ansible#{n}" do |cf|
      cf.vm.box = "centos/7"
      cf.vm.network "private_network", ip: "192.168.33.1#{n}"
      cf.vm.hostname = "ansible#{n}"
      cf.vm.provider "virtualbox" do |v|
        v.name = cf.vm.hostname
      end
    end
  end

  config.vm.define "ubuntu" do |cf|
    cf.vm.box = "ubuntu/bionic64"
    cf.vm.network "private_network", ip: "192.168.33.13"
    cf.vm.hostname = "ubuntu"
    cf.vm.provider "virtualbox" do |v|
      v.name = cf.vm.hostname
      v.memory = 512
      v.cpus = 1
    end
  end
end
